-- ============================================================
-- COMPRAS (nota de compra estilo GestãoClick: /compras/nova)
-- Rode no Supabase → SQL Editor → New query → colar → Run
-- ============================================================

CREATE TABLE IF NOT EXISTS compras (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  filial_id             UUID,
  numero                BIGINT GENERATED BY DEFAULT AS IDENTITY,
  fornecedor_id         UUID REFERENCES fornecedores(id),
  numero_nfe            TEXT,
  data_emissao          DATE DEFAULT CURRENT_DATE,
  situacao              TEXT NOT NULL DEFAULT 'em_aberto'
                        CHECK (situacao IN ('em_aberto','em_andamento','confirmada','cancelada')),
  transportadora        TEXT,
  frete                 NUMERIC(10,2) DEFAULT 0,
  frete_soma            BOOLEAN DEFAULT true,
  desconto              NUMERIC(10,2) DEFAULT 0,
  impostos              NUMERIC(10,2) DEFAULT 0,
  total_produtos        NUMERIC(10,2) DEFAULT 0,
  total                 NUMERIC(10,2) DEFAULT 0,
  pagamento             TEXT DEFAULT 'a_vista',   -- a_vista | parcelado
  parcelas              JSONB,                    -- [{"n":1,"vencimento":"2026-10-28","valor":100.00}]
  observacoes           TEXT,
  observacoes_internas  TEXT,
  usuario_id            UUID,
  usuario_nome          TEXT,
  confirmada_em         TIMESTAMPTZ,
  created_at            TIMESTAMPTZ DEFAULT NOW(),
  updated_at            TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS compra_itens (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  compra_id   UUID NOT NULL REFERENCES compras(id) ON DELETE CASCADE,
  produto_id  UUID REFERENCES produtos(id),
  descricao   TEXT NOT NULL,
  detalhes    TEXT,
  quantidade  INTEGER NOT NULL DEFAULT 1,
  unidade     TEXT DEFAULT 'un',
  custo_unit  NUMERIC(10,2) NOT NULL DEFAULT 0,
  desconto    NUMERIC(10,2) DEFAULT 0,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_compras_created ON compras(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_compra_itens_compra ON compra_itens(compra_id);

-- Acesso para usuários autenticados (mesmo padrão do recondicionamento)
ALTER TABLE compras ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS compras_autenticado ON compras;
CREATE POLICY compras_autenticado ON compras
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

ALTER TABLE compra_itens ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS compra_itens_autenticado ON compra_itens;
CREATE POLICY compra_itens_autenticado ON compra_itens
  FOR ALL TO authenticated USING (true) WITH CHECK (true);
